# http://www.appveyor.com/docs/appveyor-yml

# branches:
#   only:
#     - main
#     - v7

clone_depth: 5
version: '{build}'
build: off
deploy: off
cache:
  - "%LOCALAPPDATA%\\Yarn"

environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'
    - nodejs_version: '14'

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - yarn --version
  - yarn run check:all
