# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
    - v5

clone_depth: 5
version: "{build}"
build: off
deploy: off
cache:
 - "%LOCALAPPDATA%\\Yarn"

environment:
  matrix:
  - nodejs_version: 6
  - nodejs_version: 8
  - nodejs_version: 10
  - nodejs_version: 12

platform:
  - x86
  - x64


install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - yarn --version
  - cmd: "yarn test"
